### ISSUE TITLE
Bug report: cli not working

### ISSUE THREAD

**Issue by fritx** [jaywcjlove/generated-badges#15]
Hi, I'm trying with the cli but seems the bin command is not specified:

```sh
npm i -g generated-badges
generated-badges ...
>> command not found: generated-badges
```

If I try to modify this line (adding `.js` extension), and npm link in the cloned repo, it works:

```diff
  "bin": {
-    "generated-badges": "lib/bin",
+    "generated-badges": "lib/bin.js",
-    "generated-badges-cli": "lib/bin"
+    "generated-badges-cli": "lib/bin.js"
  },
```

Btw, the entire lib directory is not published since 1.0.1

https://unpkg.com/browse/generated-badges@1.0.0/
https://unpkg.com/browse/generated-badges@1.0.1/

What node package manager are you using?
I've tried both npm and pnpm and got the problem above

**Comment by jaywcjlove** [comment]
@fritx Upgrade `v1.0.7`

**Comment by fritx** [comment]
You are so :rocket: !

**Comment by fritx** [comment]
Also, finally get it to work with two more patches:

```sh
generated-badges -l foobar -s 666 --output build/badges/foobar.svg
```

1. 

```diff
-  if (argvs.gradient.length === 1) {
+  if (argvs.gradient && argvs.gradient.length === 1) {
    argvs.color = argvs.gradient[0];
  }
```

fixing:

```plain
/Users/fritx/g/generated-badges/lib/bin.js:48
    if (argvs.gradient.length === 1) {
                       ^

TypeError: Cannot read properties of undefined (reading 'length')
    at run (/Users/fritx/g/generated-badges/lib/bin.js:48:24)
    at Object.<anonymous> (/Users/fritx/g/generated-badges/lib/bin.js:73:1)
```

2.

```diff

  let svgString = badgen({
    label: argvs.label,
    labelColor: argvs.labelColor,
-    status: argvs.status,
+    status: String(argvs.status),
```

fixing:

```
TypeError: <status> must be string
    at L (/Users/fritx/g/generated-badges/node_modules/badgen/dist/index.js:57:257)
    at V (/Users/fritx/g/generated-badges/node_modules/badgen/dist/index.js:1:26491)
    at run (/Users/fritx/g/generated-badges/lib/bin.js:54:41)
```

**Comment by jaywcjlove** [comment]
@fritx Upgrade `v1.0.8`

**Comment by fritx** [comment]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/6647633/197112791-68a46cfb-95f7-4e54-a04b-ecf19f6e3c57.png">

hey @jaywcjlove the problem is not fixed. I guess you should also execute `npm run build` before `npm-publish` in the automated workflow
https://github.com/jaywcjlove/generated-badges/blob/main/.github/workflows/ci.yml#L163-L164

otherwise, the dist files still missing in the published npm-package

**Comment by jaywcjlove** [comment]
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/1680273/197113296-4acd61e4-6092-49d0-9d3b-fee1e1b7011e.png">

https://unpkg.com/browse/generated-badges@1.0.8/

Maybe I'm too fast

@fritx

**Comment by jaywcjlove** [comment]
@fritx problem found

**Comment by jaywcjlove** [comment]
@fritx https://unpkg.com/browse/generated-badges@1.0.9/

**Comment by jaywcjlove** [comment]
@fritx Upgrade `v1.0.9`

**Comment by fritx** [comment]
> @fritx Upgrade `v1.0.9`

Thanks. It works for me now. @jaywcjlove
